---
gas_docker_fout_settings_defaults: &gas_docker_fout_settings_defaults
  SINAP_TIMING_AREA_PREFIX: ""
  SINAP_TIMING_AUTOSAVE_CONTAINER_DIR: "/opt/epics/startup/ioc/sinap-timing-epics-ioc/iocBoot/ioctiming/autosave"
  SINAP_TIMING_AUTOSAVE_DIR: "{{ gas_docker_autosave_root_directory }}/Fout"
  SINAP_TIMING_CONTAINER_NAME: "sinap-timing-epics-ioc"
  SINAP_TIMING_DEVICE_PREFIX: ""
  SINAP_TIMING_IMAGE_BASE: "dockerregistry.lnls-sirius.com.br/gas/sinap-timing-epics-ioc"
  SINAP_TIMING_IMAGE_TAG: "v3.5.2-rc1-base-3.15-debian-9.13"
  SINAP_TIMING_INSTANCE: ""
  SINAP_TIMING_IP: ""
  SINAP_TIMING_PORT: ""
  SINAP_TIMING_TELNET_PORT: ""
  SINAP_TIMING_PLACEMENT:
    CONSTRAINTS:
      - node.hostname != CA-RaCtrl-CO-Srv-1
      - node.hostname != LA-RaCtrl-CO-Srv-1
      - node.hostname != TA-TiRack-CO-FWSrv-1
  STACK_NAME: ""

gas_docker_fout_settings:
  - <<: *gas_docker_fout_settings_defaults
    SINAP_TIMING_AREA_PREFIX: "CA-RaTim:"
    SINAP_TIMING_DEVICE_PREFIX: "TI-Fout-1:"
    SINAP_TIMING_INSTANCE: "FOUT1"
    SINAP_TIMING_IP: "CA-Tim-Fout-1"
    SINAP_TIMING_PORT: "50116"
    STACK_NAME: "Fout-CA-RaTim-1"

  - <<: *gas_docker_fout_settings_defaults
    SINAP_TIMING_AREA_PREFIX: "CA-RaTim:"
    SINAP_TIMING_DEVICE_PREFIX: "TI-Fout-2:"
    SINAP_TIMING_INSTANCE: "FOUT2"
    SINAP_TIMING_IP: "CA-Tim-Fout-2"
    SINAP_TIMING_PORT: "50118"
    STACK_NAME: "Fout-CA-RaTim-2"

  - <<: *gas_docker_fout_settings_defaults
    SINAP_TIMING_AREA_PREFIX: "CA-RaTim:"
    SINAP_TIMING_DEVICE_PREFIX: "TI-Fout-3:"
    SINAP_TIMING_INSTANCE: "FOUT3"
    SINAP_TIMING_IP: "CA-Tim-Fout-3"
    SINAP_TIMING_PORT: "50120"
    STACK_NAME: "Fout-CA-RaTim-3"

  - <<: *gas_docker_fout_settings_defaults
    SINAP_TIMING_AREA_PREFIX: "CA-RaTim:"
    SINAP_TIMING_DEVICE_PREFIX: "TI-Fout-4:"
    SINAP_TIMING_INSTANCE: "FOUT4"
    SINAP_TIMING_IP: "CA-Tim-Fout-4"
    SINAP_TIMING_PORT: "50103"
    STACK_NAME: "Fout-CA-RaTim-4"

  - <<: *gas_docker_fout_settings_defaults
    SINAP_TIMING_AREA_PREFIX: "CA-RaTim:"
    SINAP_TIMING_DEVICE_PREFIX: "TI-Fout-5:"
    SINAP_TIMING_INSTANCE: "FOUT5"
    SINAP_TIMING_IP: "CA-Tim-Fout-5"
    SINAP_TIMING_PORT: "50102"
    STACK_NAME: "Fout-CA-RaTim-5"

  - <<: *gas_docker_fout_settings_defaults
    SINAP_TIMING_AREA_PREFIX: "RA-RaMO:"
    SINAP_TIMING_DEVICE_PREFIX: "TI-Fout:"
    SINAP_TIMING_INSTANCE: "FOUT6"
    SINAP_TIMING_IP: "RA-MO-Fout"
    SINAP_TIMING_PORT: "50115"
    STACK_NAME: "Fout-RA-MO"
