ntp_timezone: 'America/Sao_Paulo'
ntp_pool: None # ntp_servers entries as 'server' instead of 'pool'
ntp_servers:
  - '10.128.255.3 iburst minpoll 3 maxpoll 3'
  - '10.128.255.4 iburst minpoll 3 maxpoll 3'
  - '10.128.255.5 iburst minpoll 3 maxpoll 3'

apt_packages:
  - gettext-base
  - git
  - tree
  - vim
