# General NTP/locale settings
config_system_locale: 'en_US.UTF-8'
config_system_language: 'en_US.UTF-8'

ntp_timezone: 'America/Sao_Paulo'

# General usage packages
apt_packages:
  # Python
  - python3
  - python3-pip

  # generate certs, utilities
  - openssl

  # Filesystem Packages
  - fuse
  - autofs

  # locales
  - locales

  # utilities
  - tree
  - nmap

# General usage Python packages
pip_packages:
  - pre-commit

# Neovim config
nvim_plugins_pip:
  # nvim
  - mdformat
  - mdformat-gfm
  - neovim

  # nvim lsp
  - python-lsp-server
  - pyls-flake8
  - pylsp-mypy
  - pyls-isort
  - python-lsp-black
  - pylsp-rope
  - rope

  # python dev
  - black
  - mypy
  - flake8


nvim_apt_packages:
  # c/c++ lint
  - clangd

  # Node utilities
  - nodejs
  - npm


nvim_checksum: sha256:ef9056e05ef6a4c1d0cdb8b21f79261703122c0fd31f23f782158d326fdadbf5
nvim_url: https://github.com/neovim/neovim/releases/download/v0.6.1/nvim.appimage

# Glusterfs
glusterfs_apt_packages:
  - glusterfs-server
  - glusterfs-client
  - glusterfs-common
