epics_base_version:
epics_base: /opt/epics-R3.15.5/base
epics_modules: /opt/epics-R3.15.5/epics/modules
epics_module_asyn: asyn4-35
epics_module_autosave: autosave-R5-9
epics_module_streamdevice: StreamDevice-2.7.11
epics_module_calc: synApps/calc-R3-7-1
