---
- become: true
  hosts: all
  tasks:
    # -----------------------------------------
    # Fix trouble makers
    - name: Remove ssh banner
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^Banner .*$'
        replace: '#Banner none'
      register: banner_removed

    - name: Remove bell from inputrc
      replace:
        path: /etc/inputrc
        regexp: '^# set bell-style none$'
        replace: 'set bell-style none'

    - name: Restart sshd applying sshd_config changes
      service:
        state: restarted
        name: sshd
      when: banner_removed.changed

    - name: Get the list of services
      service_facts:

    - name: Stop unwanted services
      service:
        state: stopped
        enabled: no
        name: "{{ item }}"
      with_items: "{{ services_disabled }}"
      when: item in ansible_facts.services

    # -----------------------------------------
    # Basic packages
    - name: Basic packages
      apt:
        pkg: "{{ apt_packages }}"
      when: ansible_os_family == 'Debian'

    # -----------------------------------------
    # NTP
    - include_role:
        name: ansible-role-ntp

