---
- connection: local
  become: false
  hosts: localhost

  vars:
    setup_zsh: true
    setup_fonts: true
    setup_nvim: true
    setup_alacritty: false

    apt_packages:
      # c/c++ lint
      - clangd

      # node utilities
      - nodejs

      # python
      - python3
      - python3-pip
      
      # generate certs, utilities
      - openssl

      # fuse
      - fuse
      - libfuse2
      - libfuse2-udeb

    pip_packages:
      # nvim
      - mdformat
      - mdformat-gfm
      - neovim

      # nvim lsp
      - python-lsp-server
      - pyls-flake8
      - pylsp-mypy
      - pyls-isort
      - python-lsp-black
      - pylsp-rope
      - rope

      # python dev
      - black
      - mypy
      - flake8

    conda_group:
      - name: conda # Conda group
        gid: 1100

  tasks:
    - name: Install general usage
      apt:
        state: latest
        pkg: "{{ apt_packages }}"

    - name: Install python3 packages
      pip:
        executable: pip3
        name: "{{ pip_packages }}"
        state: latest

    - name: Create a conda group for multi user install
      ansible.builtin.group:
        name: "{{ conda_group.name }}"
        gid: "{{ conda_group.gid }}"
        state: presentA

    - name: Install neovim
      dest: /usr/local/bin/nvim
      force: yes
      url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
      checksum: sha256:f4d32d032ffe00d1e7becaec2473115e672fbc343531be27670a11785fe7dc9c
      mode: u=rx,g=rx,o=rx

    - name: Change conda permissions
      file:
        path: /opt/conda
        owner: root
        group: "{{ conda_group.name }}"
        mode: '0775'

  roles:
    - ansible-role-ntp
    - ansible-role-docker
    - ansible-role-glusterfs
    - ansible-role-conda
