---
- become: true
  hosts: all

  tasks:
    # -----------------------------------------
    # Basic setup
    - name: Install general usage
      apt:
        state: latest
        pkg: "{{ apt_packages }}"
      when: ansible_os_family == 'Debian'

    - name: Install setuptools
      pip:
        executable: /usr/bin/pip3
        name: setuptools

    - name: Install python3 packages
      pip:
        executable: /usr/bin/pip3
        name: "{{ pip_packages }}"
        state: latest

    # -----------------------------------------
    # NTP
    - include_role:
        name: ansible-role-ntp

    # -----------------------------------------
    # Locale
    - name: Locale settings
      include_tasks: tasks/locale.yml

    # -----------------------------------------
    # Conda
    - include_role:
        name: ansible-role-conda

    # -----------------------------------------
    # Docker
    - include_role:
        name: ansible-role-docker
      vars:
        docker_restart_handler_state: started
        docker_package: "docker-ce=5:20.10.12~3-0~debian-bullseye"

    # -----------------------------------------
    # Glusterfs
    - name: Glusterfs packages
      apt:
        pkg: "{{ glusterfs_apt_packages }}"
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start Glusterfs service
      service:
        name: glusterd
        state: started
        enabled: yes
