---
# - connection: local
- become: true
  hosts: all #localhost

  vars:
    setup_zsh: true
    setup_fonts: true
    setup_nvim: true
    setup_alacritty: false

    apt_packages:
      # c/c++ lint
      - clangd

      # Node utilities
      - nodejs
      - npm

      # Python
      - python3
      - python3-pip

      # generate certs, utilities
      - openssl

      # Filesystem Packages
      - fuse
      - libfuse2
      - autofs

      - locales

    pip_packages:
      # nvim
      - mdformat
      - mdformat-gfm
      - neovim

      # nvim lsp
      - python-lsp-server
      - pyls-flake8
      - pylsp-mypy
      - pyls-isort
      - python-lsp-black
      - pylsp-rope
      - rope

      # python dev
      - black
      - mypy
      - flake8
      - pre-commit

    # Conda gid and name for multi user /opt install
    conda_group_name: conda
    conda_group_gid: 1100

    config_system_locale: 'pt_BR.UTF-8'
    config_system_language: 'en_US.UTF-8'

  tasks:
    # -----------------------------------------
    # Basic packages
    - name: Install general usage
      apt:
        state: latest
        pkg: "{{ apt_packages }}"

    - name: Install python3 packages
      pip:
        executable: pip3
        name: "{{ pip_packages }}"
        state: latest

    # -----------------------------------------
    # NTP
    - include_role:
        name: ansible-role-ntp

    - name: Set timezone
      timezone:
        name: America/Sao_Paulo

    - name: Ensure a locale exists
      locale_gen:
        name: "{{ config_system_locale }}"
        state: present

    # -----------------------------------------
    # Neovim
    - name: Install neovim
      get_url:
        dest: /usr/local/bin/nvim
        force: yes
        url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
        checksum: sha256:f4d32d032ffe00d1e7becaec2473115e672fbc343531be27670a11785fe7dc9c
        mode: u=rx,g=rx,o=rx

    # -----------------------------------------
    # Conda
    - include_role:
        name: ansible-role-conda

    - name: Create a conda group for multi user install
      group:
        name: "{{ conda_group_name }}"
        gid: "{{ conda_group_gid }}"
        state: present

    - name: Change conda permissions
      file:
        path: /opt/conda
        owner: root
        group: "{{ conda_group_name }}"
        mode: '0775'


    # -----------------------------------------
    # Docker
    - include_role:
        name: ansible-role-docker
      vars:
        docker_restart_handler_state: started
        docker_package: "docker-ce=5:20.10.12~3-0~debian-bullseye"

    # -----------------------------------------
    # Glusterfs
    - name: Glusterfs packages
      apt:
        pkg:
          - glusterfs-server
          - glusterfs-client
          - glusterfs-common

    - name: Start Glusterfs service
      service:
        name: glusterd
        state: started
        enabled: yes
