---
# - connection: local
- become: true
  hosts: all #localhost

  vars:
    setup_zsh: true
    setup_fonts: true
    setup_nvim: true
    setup_alacritty: false

    apt_packages:
      # Python
      - python3
      - python3-pip

      # generate certs, utilities
      - openssl

      # Filesystem Packages
      - fuse
      - autofs

      - locales

    pip_packages:
      - pre-commit

    config_system_locale: 'en_US.UTF-8'
    config_system_language: 'en_US.UTF-8'

    ntp_timezone: 'America/Sao_Paulo'

    glusterfs_apt_packages:
      - glusterfs-server
      - glusterfs-client
      - glusterfs-common

    nvim_apt_packages:
      # c/c++ lint
      - clangd

      # Node utilities
      - nodejs
      - npm

    nvim_plugins_pip:
      # nvim
      - mdformat
      - mdformat-gfm
      - neovim

      # nvim lsp
      - python-lsp-server
      - pyls-flake8
      - pylsp-mypy
      - pyls-isort
      - python-lsp-black
      - pylsp-rope
      - rope

      # python dev
      - black
      - mypy
      - flake8

    nvim_checksum: sha256:ef9056e05ef6a4c1d0cdb8b21f79261703122c0fd31f23f782158d326fdadbf5
    nvim_url: https://github.com/neovim/neovim/releases/download/v0.6.1/nvim.appimage

  tasks:
    # -----------------------------------------
    # Basic setup
    - name: Install general usage
      apt:
        state: latest
        pkg: "{{ apt_packages }}"
      when: ansible_os_family == 'Debian'

    - name: Install setuptools
      pip:
        executable: /usr/bin/pip3
        name: setuptools

    - name: Install python3 packages
      pip:
        executable: /usr/bin/pip3
        name: "{{ pip_packages }}"
        state: latest

    # -----------------------------------------
    # NTP
    - include_role:
        name: ansible-role-ntp

    # -----------------------------------------
    # Locale
    - name: Locale settings
      include_tasks: tasks/locale.yml

    # -----------------------------------------
    # Conda
    - include_role:
        name: ansible-role-conda

    # -----------------------------------------
    # Docker
    - include_role:
        name: ansible-role-docker
      vars:
        docker_restart_handler_state: started
        docker_package: "docker-ce=5:20.10.12~3-0~debian-bullseye"

    # -----------------------------------------
    # Glusterfs
    - name: Glusterfs packages
      apt:
        pkg: "{{ glusterfs_apt_packages }}"
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start Glusterfs service
      service:
        name: glusterd
        state: started
        enabled: yes
