---
- connection: local
  become: true
  hosts: localhost

  vars:
    setup_zsh: true
    setup_fonts: true
    setup_nvim: true
    setup_alacritty: false

    apt_packages:
      # c/c++ lint
      - clangd

      # node utilities
      - nodejs
      - npm

      # python
      - python3
      - python3-pip

      # generate certs, utilities
      - openssl

      # fuse
      - fuse
      - libfuse2

    pip_packages:
      # nvim
      - mdformat
      - mdformat-gfm
      - neovim

      # nvim lsp
      - python-lsp-server
      - pyls-flake8
      - pylsp-mypy
      - pyls-isort
      - python-lsp-black
      - pylsp-rope
      - rope

      # python dev
      - black
      - mypy
      - flake8
      - pre-commit

    # Conda gid and name for multi user /opt install
    conda_group_name: conda
    conda_group_gid: 1100


  tasks:
    # -----------------------------------------
    # Basic packages
    - name: Install general usage
      apt:
        state: latest
        pkg: "{{ apt_packages }}"

    - name: Install python3 packages
      pip:
        executable: pip3
        name: "{{ pip_packages }}"
        state: latest

    # -----------------------------------------
    # NTP
    - include_role:
        name: ansible-role-ntp

    # -----------------------------------------
    # Neovim
    - name: Install neovim
      get_url:
        dest: /usr/local/bin/nvim
        force: yes
        url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
        checksum: sha256:f4d32d032ffe00d1e7becaec2473115e672fbc343531be27670a11785fe7dc9c
        mode: u=rx,g=rx,o=rx

    # -----------------------------------------
    # Conda
    - include_role:
        name: ansible-role-conda

    - name: Create a conda group for multi user install
      group:
        name: "{{ conda_group_name }}"
        gid: "{{ conda_group_gid }}"
        state: present

    - name: Change conda permissions
      file:
        path: /opt/conda
        owner: root
        group: "{{ conda_group_name }}"
        mode: '0775'


    # -----------------------------------------
    # Glusterfs & Docker
    - include_role:
        name: ansible-role-docker
      vars:
        docker_restart_handler_state: started
        docker_package: "docker-ce=5:20.10.12~3-0~debian-bullseye"

    - include_role:
        name: ansible-role-glusterfs
